# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  proyecto: 'WebApiAutores/WebApiAutores.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: CmdLine@2
  displayName: 'Installing EF Core CLI'
  inputs:
   script: 'dotnet tool install -- global dotnet-ef'

